/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -a dbus_adaptor.h:dbus_adaptor.cpp info.dolezel.fatrat.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FatratAdaptor
 */

FatratAdaptor::FatratAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FatratAdaptor::~FatratAdaptor()
{
    // destructor
}

void FatratAdaptor::addTransfers(const QString &uri)
{
    // handle method call info.dolezel.fatrat.addDownload
    QMetaObject::invokeMethod(parent(), "addTransfer", Qt::QueuedConnection, Q_ARG(QString, uri));
}

