/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_dolezel_fatrat_plugins_FRDownloadPlugin */

#ifndef _Included_info_dolezel_fatrat_plugins_FRDownloadPlugin
#define _Included_info_dolezel_fatrat_plugins_FRDownloadPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    setMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_setMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    setState
 * Signature: (Linfo/dolezel/fatrat/plugins/FRDownloadPlugin/State;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_setState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    fetchPage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_fetchPage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    startDownload
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_startDownload
  (JNIEnv *, jobject, jstring);

/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    startWait
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_startWait
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     info_dolezel_fatrat_plugins_FRDownloadPlugin
 * Method:    logMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_info_dolezel_fatrat_plugins_FRDownloadPlugin_logMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
